title: System Architecture Framework
description: A scalable SysML Based Framework to foster MBSE for multiple Modeling Tools!
theme: just-the-docs
source: src

url: https://saf.gfse.org


logo: "/assets/images/Banner_SAF_gross.png"


plugins:
  - jekyll-relative-links



relative_links:
  enabled:     true

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  todo:
    title: ToDo
    color: purple
  warning:
    title: Warning
    color: red